export const dummyProspects = [
  {
    id: 1,
    name: "John Doe",
    organisation: "Tech Corp",
    title: "Software Engineer",
    linkedinUrl: "https://www.linkedin.com/in/johndoe",
    email: "john.doe@techcorp.com",
    activeCampaign: "Summer Outreach",
    status: "For Approval",
    phone: "+1 (555) 123-4567",
    linkedinHeadline: "Passionate Software Engineer | Full Stack Developer",
    linkedinSummary: "Experienced software engineer with a focus on web technologies and cloud computing.",
    location: "San Francisco, CA",
    connections: 500,
    followerCount: 1000,
    organisationLinkedinUrl: "https://www.linkedin.com/company/techcorp",
    website: "https://www.techcorp.com",
    organisationDescription: "Leading technology solutions provider",
    industry: "Information Technology",
    organisationLocation: "Silicon Valley, CA",
    employeeCount: "1001-5000",
    size: "Large Enterprise",
    type: "Public Company",
    organisationFollowerCount: 50000,
    activityStream: [
      { action: "Added to campaign", date: "2023-03-01T10:00:00Z" },
      { action: "Connection request sent", date: "2023-03-02T14:30:00Z" },
      { action: "Connection accepted", date: "2023-03-05T09:15:00Z" },
      { action: "First message sent", date: "2023-03-07T11:00:00Z" },
      { action: "Reply received", date: "2023-03-10T16:45:00Z" }
    ]
  },
  {
    id: 2,
    name: "Jane Smith",
    organisation: "Innovate Inc",
    title: "Product Manager",
    linkedinUrl: "https://www.linkedin.com/in/janesmith",
    email: "jane.smith@innovateinc.com",
    activeCampaign: "Q4 Sales Push",
    status: "Connected",
    phone: "+1 (555) 987-6543",
    linkedinHeadline: "Product Manager | Innovation Enthusiast",
    linkedinSummary: "Experienced product manager with a track record of launching successful products in the tech industry.",
    location: "New York, NY",
    connections: 750,
    followerCount: 1500,
    organisationLinkedinUrl: "https://www.linkedin.com/company/innovateinc",
    website: "https://www.innovateinc.com",
    organisationDescription: "Cutting-edge innovation company",
    industry: "Technology",
    organisationLocation: "New York City, NY",
    employeeCount: "501-1000",
    size: "Mid-Market",
    type: "Private Company",
    organisationFollowerCount: 25000,
    activityStream: [
      { action: "Added to campaign", date: "2023-02-15T09:00:00Z" },
      { action: "Connection request sent", date: "2023-02-16T13:45:00Z" },
      { action: "Connection accepted", date: "2023-02-18T10:30:00Z" },
      { action: "First message sent", date: "2023-02-20T14:00:00Z" },
      { action: "Reply received", date: "2023-02-23T11:15:00Z" },
      { action: "Follow-up message sent", date: "2023-02-25T16:30:00Z" }
    ]
  },
  {
    id: 3,
    name: "Bob Johnson",
    organisation: "Global Solutions",
    title: "Sales Director",
    linkedinUrl: "https://www.linkedin.com/in/bobjohnson",
    email: "bob.johnson@globalsolutions.com",
    activeCampaign: "New Product Launch",
    status: "Meeting Scheduled",
    phone: "+1 (555) 246-8135",
    linkedinHeadline: "Sales Director | B2B Solutions Expert",
    linkedinSummary: "Results-driven sales director with over 15 years of experience in B2B software sales.",
    location: "Chicago, IL",
    connections: 1000,
    followerCount: 2000,
    organisationLinkedinUrl: "https://www.linkedin.com/company/globalsolutions",
    website: "https://www.globalsolutions.com",
    organisationDescription: "Worldwide business solutions provider",
    industry: "Business Services",
    organisationLocation: "Chicago, IL",
    employeeCount: "5001-10000",
    size: "Enterprise",
    type: "Public Company",
    organisationFollowerCount: 75000,
    activityStream: [
      { action: "Added to campaign", date: "2023-01-10T08:30:00Z" },
      { action: "Connection request sent", date: "2023-01-11T11:00:00Z" },
      { action: "Connection accepted", date: "2023-01-13T14:45:00Z" },
      { action: "First message sent", date: "2023-01-15T09:30:00Z" },
      { action: "Reply received", date: "2023-01-18T13:15:00Z" },
      { action: "Follow-up call scheduled", date: "2023-01-20T10:00:00Z" },
      { action: "Meeting scheduled", date: "2023-01-25T15:30:00Z" }
    ]
  },
  {
    id: 4,
    name: "Emily Chen",
    organisation: "HealthTech Solutions",
    title: "Chief Medical Officer",
    linkedinUrl: "https://www.linkedin.com/in/emilychen",
    email: "emily.chen@healthtechsolutions.com",
    activeCampaign: "Healthcare Innovation",
    status: "Interested",
    phone: "+1 (555) 789-0123",
    linkedinHeadline: "Chief Medical Officer | Digital Health Innovator",
    linkedinSummary: "Experienced physician and healthcare technology leader driving innovation in patient care.",
    location: "Boston, MA",
    connections: 1200,
    followerCount: 3000,
    organisationLinkedinUrl: "https://www.linkedin.com/company/healthtechsolutions",
    website: "https://www.healthtechsolutions.com",
    organisationDescription: "Innovative healthcare technology solutions",
    industry: "Healthcare",
    organisationLocation: "Boston, MA",
    employeeCount: "201-500",
    size: "Mid-Market",
    type: "Private Company",
    organisationFollowerCount: 40000,
    activityStream: [
      { action: "Added to campaign", date: "2023-04-05T09:00:00Z" },
      { action: "Connection request sent", date: "2023-04-06T11:30:00Z" },
      { action: "Connection accepted", date: "2023-04-08T14:15:00Z" },
      { action: "First message sent", date: "2023-04-10T10:00:00Z" },
      { action: "Reply received", date: "2023-04-12T16:30:00Z" },
      { action: "Follow-up message sent", date: "2023-04-15T11:45:00Z" }
    ]
  },
  {
    id: 5,
    name: "Michael Wong",
    organisation: "Green Energy Co",
    title: "Sustainability Director",
    linkedinUrl: "https://www.linkedin.com/in/michaelwong",
    email: "michael.wong@greenenergy.com",
    activeCampaign: "Renewable Energy Push",
    status: "Connection Request Sent",
    phone: "+1 (555) 321-6547",
    linkedinHeadline: "Sustainability Director | Renewable Energy Expert",
    linkedinSummary: "Passionate about driving sustainable practices and renewable energy adoption in businesses.",
    location: "Portland, OR",
    connections: 800,
    followerCount: 1800,
    organisationLinkedinUrl: "https://www.linkedin.com/company/greenenergy",
    website: "https://www.greenenergy.com",
    organisationDescription: "Leading provider of renewable energy solutions",
    industry: "Energy & Environment",
    organisationLocation: "Portland, OR",
    employeeCount: "501-1000",
    size: "Mid-Market",
    type: "Private Company",
    organisationFollowerCount: 60000,
    activityStream: [
      { action: "Added to campaign", date: "2023-05-02T08:45:00Z" },
      { action: "Connection request sent", date: "2023-05-03T13:20:00Z" }
    ]
  }
];