export const dummyProspects = [
  {
    id: 1,
    name: "John Doe",
    organisation: "Tech Corp",
    title: "Software Engineer",
    linkedinUrl: "https://linkedin.com/in/johndoe",
    email: "john.doe@techcorp.com",
    activeCampaign: "Summer Outreach",
    status: "Connected",
    firstName: "John",
    lastName: "Doe",
    phone: "+1 123-456-7890",
    linkedinHeadline: "Passionate Software Engineer | AI Enthusiast",
    linkedinSummary: "Experienced software engineer with a focus on AI and machine learning...",
    location: "San Francisco, CA",
    connections: 500,
    followerCount: 1000,
    organisationLinkedinUrl: "https://linkedin.com/company/techcorp",
    website: "https://techcorp.com",
    organisationDescription: "Leading technology solutions provider...",
    industry: "Information Technology",
    organisationLocation: "Silicon Valley, CA",
    employeeCount: 1000,
    size: "Medium Enterprise",
    type: "Public Company",
    organisationFollowerCount: 50000,
    activityStream: [
      { date: "2023-03-15T09:30:00Z", action: "Added to campaign 'Summer Outreach'" },
      { date: "2023-03-16T14:45:00Z", action: "Connection request sent" },
      { date: "2023-03-18T11:20:00Z", action: "Connection accepted" },
      { date: "2023-03-20T16:00:00Z", action: "Initial message sent" },
    ]
  },
  {
    id: 2,
    name: "Jane Smith",
    organisation: "Innovate Inc",
    title: "Product Manager",
    linkedinUrl: "https://linkedin.com/in/janesmith",
    email: "jane.smith@innovateinc.com",
    activeCampaign: "Q4 Sales Push",
    status: "For Approval",
    firstName: "Jane",
    lastName: "Smith",
    phone: "+1 987-654-3210",
    linkedinHeadline: "Product Manager | Innovation Enthusiast",
    linkedinSummary: "Experienced product manager with a passion for innovative solutions...",
    location: "New York, NY",
    connections: 750,
    followerCount: 1500,
    organisationLinkedinUrl: "https://linkedin.com/company/innovateinc",
    website: "https://innovateinc.com",
    organisationDescription: "Leading innovation company...",
    industry: "Technology",
    organisationLocation: "New York, NY",
    employeeCount: 500,
    size: "Small Enterprise",
    type: "Private Company",
    organisationFollowerCount: 30000,
    activityStream: [
      { date: "2023-04-01T10:00:00Z", action: "Added to campaign 'Q4 Sales Push'" },
      { date: "2023-04-02T11:30:00Z", action: "Pending approval" },
    ]
  },
  {
    id: 3,
    name: "Michael Johnson",
    organisation: "Global Solutions",
    title: "Sales Director",
    linkedinUrl: "https://linkedin.com/in/michaeljohnson",
    email: "michael.johnson@globalsolutions.com",
    activeCampaign: "Enterprise Outreach",
    status: "Interested",
    firstName: "Michael",
    lastName: "Johnson",
    phone: "+1 555-123-4567",
    linkedinHeadline: "Sales Director | B2B Solutions Expert",
    linkedinSummary: "Experienced sales director with a track record of closing enterprise deals...",
    location: "Chicago, IL",
    connections: 1000,
    followerCount: 2000,
    organisationLinkedinUrl: "https://linkedin.com/company/globalsolutions",
    website: "https://globalsolutions.com",
    organisationDescription: "Worldwide B2B solutions provider...",
    industry: "Business Services",
    organisationLocation: "Chicago, IL",
    employeeCount: 5000,
    size: "Large Enterprise",
    type: "Public Company",
    organisationFollowerCount: 100000,
    activityStream: [
      { date: "2023-05-01T09:00:00Z", action: "Added to campaign 'Enterprise Outreach'" },
      { date: "2023-05-03T14:30:00Z", action: "Initial message sent" },
      { date: "2023-05-05T11:15:00Z", action: "Positive reply received" },
    ]
  },
  {
    id: 4,
    name: "Emily Brown",
    organisation: "EcoTech Solutions",
    title: "Environmental Engineer",
    linkedinUrl: "https://linkedin.com/in/emilybrown",
    email: "emily.brown@ecotechsolutions.com",
    activeCampaign: "Green Tech Initiative",
    status: "For Approval",
    firstName: "Emily",
    lastName: "Brown",
    phone: "+1 444-555-6666",
    linkedinHeadline: "Environmental Engineer | Sustainable Technology Advocate",
    linkedinSummary: "Passionate about developing eco-friendly technologies...",
    location: "Portland, OR",
    connections: 600,
    followerCount: 800,
    organisationLinkedinUrl: "https://linkedin.com/company/ecotechsolutions",
    website: "https://ecotechsolutions.com",
    organisationDescription: "Innovative green technology solutions...",
    industry: "Environmental Services",
    organisationLocation: "Portland, OR",
    employeeCount: 200,
    size: "Small Enterprise",
    type: "Private Company",
    organisationFollowerCount: 15000,
    activityStream: [
      { date: "2023-06-10T10:00:00Z", action: "Added to campaign 'Green Tech Initiative'" },
      { date: "2023-06-11T15:45:00Z", action: "Pending approval" },
    ]
  },
  {
    id: 5,
    name: "David Lee",
    organisation: "FinTech Innovations",
    title: "Chief Technology Officer",
    linkedinUrl: "https://linkedin.com/in/davidlee",
    email: "david.lee@fintechinnovations.com",
    activeCampaign: "Financial Tech Summit",
    status: "Meeting Scheduled",
    firstName: "David",
    lastName: "Lee",
    phone: "+1 777-888-9999",
    linkedinHeadline: "CTO | FinTech Visionary",
    linkedinSummary: "Driving technological advancements in the financial sector...",
    location: "New York, NY",
    connections: 1500,
    followerCount: 3000,
    organisationLinkedinUrl: "https://linkedin.com/company/fintechinnovations",
    website: "https://fintechinnovations.com",
    organisationDescription: "Revolutionizing financial services through technology...",
    industry: "Financial Technology",
    organisationLocation: "New York, NY",
    employeeCount: 300,
    size: "Medium Enterprise",
    type: "Private Company",
    organisationFollowerCount: 50000,
    activityStream: [
      { date: "2023-07-01T09:30:00Z", action: "Added to campaign 'Financial Tech Summit'" },
      { date: "2023-07-03T11:00:00Z", action: "Connection request sent" },
      { date: "2023-07-05T14:20:00Z", action: "Connection accepted" },
      { date: "2023-07-07T16:45:00Z", action: "Meeting scheduled" },
    ]
  },
  {
    id: 6,
    name: "Sarah Wilson",
    organisation: "HealthTech Solutions",
    title: "Head of Product",
    linkedinUrl: "https://linkedin.com/in/sarahwilson",
    email: "sarah.wilson@healthtechsolutions.com",
    activeCampaign: "Healthcare Innovation",
    status: "Connected",
    firstName: "Sarah",
    lastName: "Wilson",
    phone: "+1 222-333-4444",
    linkedinHeadline: "Product Leader | Healthcare Technology Innovator",
    linkedinSummary: "Dedicated to improving patient outcomes through innovative health tech solutions...",
    location: "Boston, MA",
    connections: 800,
    followerCount: 1200,
    organisationLinkedinUrl: "https://linkedin.com/company/healthtechsolutions",
    website: "https://healthtechsolutions.com",
    organisationDescription: "Innovative healthcare technology solutions provider...",
    industry: "Healthcare Technology",
    organisationLocation: "Boston, MA",
    employeeCount: 150,
    size: "Small Enterprise",
    type: "Private Company",
    organisationFollowerCount: 25000,
    activityStream: [
      { date: "2023-08-01T10:15:00Z", action: "Added to campaign 'Healthcare Innovation'" },
      { date: "2023-08-03T13:30:00Z", action: "Connection request sent" },
      { date: "2023-08-05T09:45:00Z", action: "Connection accepted" },
    ]
  },
  {
    id: 7,
    name: "Robert Taylor",
    organisation: "AI Research Labs",
    title: "Lead AI Researcher",
    linkedinUrl: "https://linkedin.com/in/roberttaylor",
    email: "robert.taylor@airesearchlabs.com",
    activeCampaign: "AI Collaboration Initiative",
    status: "For Approval",
    firstName: "Robert",
    lastName: "Taylor",
    phone: "+1 999-888-7777",
    linkedinHeadline: "AI Researcher | Machine Learning Expert",
    linkedinSummary: "Pushing the boundaries of artificial intelligence and machine learning...",
    location: "Seattle, WA",
    connections: 1200,
    followerCount: 2500,
    organisationLinkedinUrl: "https://linkedin.com/company/airesearchlabs",
    website: "https://airesearchlabs.com",
    organisationDescription: "Cutting-edge AI research and development...",
    industry: "Artificial Intelligence",
    organisationLocation: "Seattle, WA",
    employeeCount: 100,
    size: "Small Enterprise",
    type: "Private Company",
    organisationFollowerCount: 40000,
    activityStream: [
      { date: "2023-09-01T11:00:00Z", action: "Added to campaign 'AI Collaboration Initiative'" },
      { date: "2023-09-02T14:30:00Z", action: "Pending approval" },
    ]
  },
  {
    id: 8,
    name: "Jennifer Martinez",
    organisation: "CloudScale Systems",
    title: "Cloud Architect",
    linkedinUrl: "https://linkedin.com/in/jennifermartinez",
    email: "jennifer.martinez@cloudscale.com",
    activeCampaign: "Cloud Migration Services",
    status: "Interested",
    firstName: "Jennifer",
    lastName: "Martinez",
    phone: "+1 111-222-3333",
    linkedinHeadline: "Cloud Architect | DevOps Enthusiast",
    linkedinSummary: "Experienced in designing and implementing scalable cloud solutions...",
    location: "Austin, TX",
    connections: 900,
    followerCount: 1800,
    organisationLinkedinUrl: "https://linkedin.com/company/cloudscalesystems",
    website: "https://cloudscalesystems.com",
    organisationDescription: "Enterprise cloud solutions and migration services...",
    industry: "Cloud Computing",
    organisationLocation: "Austin, TX",
    employeeCount: 250,
    size: "Medium Enterprise",
    type: "Private Company",
    organisationFollowerCount: 35000,
    activityStream: [
      { date: "2023-10-01T09:45:00Z", action: "Added to campaign 'Cloud Migration Services'" },
      { date: "2023-10-03T13:15:00Z", action: "Initial message sent" },
      { date: "2023-10-05T10:30:00Z", action: "Positive reply received" },
    ]
  },
  {
    id: 9,
    name: "Thomas Anderson",
    organisation: "Cyber Defense Inc",
    title: "Chief Information Security Officer",
    linkedinUrl: "https://linkedin.com/in/thomasanderson",
    email: "thomas.anderson@cyberdefense.com",
    activeCampaign: "Cybersecurity Summit",
    status: "Meeting Scheduled",
    firstName: "Thomas",
    lastName: "Anderson",
    phone: "+1 444-555-6666",
    linkedinHeadline: "CISO | Cybersecurity Expert",
    linkedinSummary: "Protecting organizations from cyber threats and ensuring data integrity...",
    location: "Washington, D.C.",
    connections: 1300,
    followerCount: 2200,
    organisationLinkedinUrl: "https://linkedin.com/company/cyberdefenseinc",
    website: "https://cyberdefenseinc.com",
    organisationDescription: "Leading provider of cybersecurity solutions and services...",
    industry: "Cybersecurity",
    organisationLocation: "Washington, D.C.",
    employeeCount: 500,
    size: "Medium Enterprise",
    type: "Public Company",
    organisationFollowerCount: 75000,
    activityStream: [
      { date: "2023-11-01T10:00:00Z", action: "Added to campaign 'Cybersecurity Summit'" },
      { date: "2023-11-03T14:30:00Z", action: "Connection request sent" },
      { date: "2023-11-05T09:15:00Z", action: "Connection accepted" },
      { date: "2023-11-07T11:45:00Z", action: "Meeting scheduled" },
    ]
  },
  {
    id: 10,
    name: "Lisa Chen",
    organisation: "BioTech Innovations",
    title: "Research Director",
    linkedinUrl: "https://linkedin.com/in/lisachen",
    email: "lisa.chen@biotechinnovations.com",
    activeCampaign: "BioTech Research Collaboration",
    status: "For Approval",
    firstName: "Lisa",
    lastName: "Chen",
    phone: "+1 777-888-9999",
    linkedinHeadline: "Biotech Research Director | Genomics Specialist",
    linkedinSummary: "Leading groundbreaking research in genomics and personalized medicine...",
    location: "San Diego, CA",
    connections: 1100,
    followerCount: 1900,
    organisationLinkedinUrl: "https://linkedin.com/company/biotechinnovations",
    website: "https://biotechinnovations.com",
    organisationDescription: "Pioneering biotech research and development...",
    industry: "Biotechnology",
    organisationLocation: "San Diego, CA",
    employeeCount: 200,
    size: "Small Enterprise",
    type: "Private Company",
    organisationFollowerCount: 30000,
    activityStream: [
      { date: "2023-12-01T11:30:00Z", action: "Added to campaign 'BioTech Research Collaboration'" },
      { date: "2023-12-02T15:45:00Z", action: "Pending approval" },
    ]
  },
  {
    id: 11,
    name: "Mark Williams",
    organisation: "Renewable Energy Solutions",
    title: "Chief Sustainability Officer",
    linkedinUrl: "https://linkedin.com/in/markwilliams",
    email: "mark.williams@renewableenergy.com",
    activeCampaign: "Green Energy Initiative",
    status: "Connected",
    firstName: "Mark",
    lastName: "Williams",
    phone: "+1 333-444-5555",
    linkedinHeadline: "CSO | Renewable Energy Advocate",
    linkedinSummary: "Driving sustainable energy solutions and corporate environmental responsibility...",
    location: "Denver, CO",
    connections: 950,
    followerCount: 1700,
    organisationLinkedinUrl: "https://linkedin.com/company/renewableenergysolutions",
    website: "https://renewableenergysolutions.com",
    organisationDescription: "Leading provider of renewable energy technologies and solutions...",
    industry: "Renewable Energy",
    organisationLocation: "Denver, CO",
    employeeCount: 300,
    size: "Medium Enterprise",
    type: "Public Company",
    organisationFollowerCount: 45000,
    activityStream: [
      { date: "2024-01-01T10:00:00Z", action: "Added to campaign 'Green Energy Initiative'" },
      { date: "2024-01-03T13:30:00Z", action: "Connection request sent" },
      { date: "2024-01-05T09:45:00Z", action: "Connection accepted" },
    ]
  },
  {
    id: 12,
    name: "Olivia Parker",
    organisation: "EdTech Innovations",
    title: "Director of Educational Technology",
    linkedinUrl: "https://linkedin.com/in/oliviaparker",
    email: "olivia.parker@edtechinnovations.com",
    activeCampaign: "Future of Learning",
    status: "For Approval",
    firstName: "Olivia",
    lastName: "Parker",
    phone: "+1 666-777-8888",
    linkedinHeadline: "EdTech Director | E-Learning Specialist",
    linkedinSummary: "Transforming education through innovative technology solutions...",
    location: "Boston, MA",
    connections: 850,
    followerCount: 1400,
    organisationLinkedinUrl: "https://linkedin.com/company/edtechinnovations",
    website: "https://edtechinnovations.com",
    organisationDescription: "Revolutionizing education with cutting-edge technology...",
    industry: "Education Technology",
    organisationLocation: "Boston, MA",
    employeeCount: 150,
    size: "Small Enterprise",
    type: "Private Company",
    organisationFollowerCount: 20000,
    activityStream: [
      { date: "2024-02-01T11:15:00Z", action: "Added to campaign 'Future of Learning'" },
      { date: "2024-02-02T14:30:00Z", action: "Pending approval" },
    ]
  }
];

export const getStatusColor = (status) => {
  const positiveStatuses = ["Connected", "Meeting Request", "Interested", "Pricing Request", "Referral to Colleague", "Future Interest"];
  const neutralStatuses = ["No Active Campaign", "Sequenced", "Connection Request Sent", "Awaiting Reply", "Needs More Information", "Neutral", "Out of Office", "Other", "N/A", "For Approval"];
  const negativeStatuses = ["Left Company", "Wrong Person", "Not Interested", "Unsubscribe/Do Not Contact"];

  if (positiveStatuses.includes(status)) return "bg-green-100 text-green-800";
  if (neutralStatuses.includes(status)) return "bg-yellow-100 text-yellow-800";
  if (negativeStatuses.includes(status)) return "bg-red-100 text-red-800";
  return "bg-gray-100 text-gray-800";
};

export const getActivityColor = (action) => {
  if (action.includes("Added to campaign")) return "text-blue-600";
  if (action.includes("Connection request sent")) return "text-yellow-600";
  if (action.includes("Connection accepted")) return "text-green-600";
  if (action.includes("message sent")) return "text-purple-600";
  if (action.includes("reply received")) return "text-indigo-600";
  return "text-gray-600";
};